### ISSUE TITLE
plot_dimred()  error

### ISSUE THREAD

**Issue by Woqo** [dynverse/dyno#111] opened 2021-06-23 13:48 UTC
Hi，
thank you for this  package! 
I would like to use it for my analysis.
But when I am trying I get this error :

> plot_dimred(model,
expression_source = dataset$expression, 
grouping = object_cellinfo)

Coloring by grouping
error: Must supply a symbol or a string as argument
Run `rlang::last_error()` to see where the error occurred.

Can you give me some advice?
Thanks!

**Comment by rcannood** [comment] 2021-06-24 13:59
Hello @Woqo !

This is a duplicate of dynverse/dynplot#54. Can you run the solution there and verify whether your issue has been solved?

Kind regards,
Robrecht

**Closed as completed** 2021-06-24 14:00 UTC
Labels: duplicate ‼️
